name: aoiwe_logger
description: A structured logging package for Dart and Flutter. Features include global log level filtering, project name prefixing, and seamless IDE debug console integration.
version: 1.0.0
homepage: https://jsontodart.cn
repository: https://github.com/Matkurban/aoiwe_logger
topics:
  - logger

environment:
  sdk: ^3.11.3

dependencies:
  meta: any

dev_dependencies:
  lints: ^6.1.0
  test: ^1.31.0
